# App
spring.application.name=travel-planner

# MongoDB Atlas (replace with your Atlas URI later)
spring.mongodb.uri=mongodb+srv://sarahfared783:KmgkbOHhHslhNgLF@sarah.pkrcodt.mongodb.net/travel_planner?retryWrites=true&w=majority

# JWT
app.jwt.secret=Hk7&fPq9zLm@3RgXuN!5Yt$WsVbEcA144
app.jwt.expiration=86400000

# CORS (Angular dev server)
app.cors.allowed-origins=http://localhost:4200

# Server
server.port=8080