# App
spring.application.name=travel-planner

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://sarahfared783:KmgkbOHhHslhNgLF@sarah.pkrcodt.mongodb.net/travel_planner?retryWrites=true&w=majority

# JWT
app.jwt.secret=Hk7&fPq9zLm@3RgXuN!5Yt$WsVbEcA144
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=*

# Server
server.port=${PORT:8080}